### ISSUE TITLE
Remove redundant /api segment from endpoint paths

### ISSUE THREAD

**Issue by riimuru** [AlgoArchiveExt/api.algoarchive.org#11]
Since the domain (api.algoarchive.org) already indicates its an api. We can simplify the paths by removing the /api segment, making the url more cleaner.

**Comment by lausan3** [comment]
Gotcha, I'll put this on the list!

**Comment by lausan3** [comment]
finished with https://github.com/AlgoArchiveExt/api.algoarchive.org/commit/660600ec3406dc4e9ebda7cea933ddb289d5b4eb
